import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from "axios"
import React from "react"

export default function Home() {
  const [nfts, setNFTS] = React.useState([])

  const handleSearch = async (value) => {
    if (value.length > 3) {

      const res = await axios.get(`https://api.reservoir.tools/search/collections/v1?name=${value}`, {
        headers: {
          "x-api-key": "demo-api-key"
        }
      })

      console.log(res)
      setNFTS(res.data.collections)
    }
  }

  console.log("nfts", nfts)

  return (
    <div className={styles.container}>
      <Head>
        <title>OWND x Rakhat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <input type="search" className='myInput' placeholder="Search" onChange={(e) => handleSearch(e.target.value)}/>
        {nfts.length > 0 &&
          <ul id="myUL">
            {nfts.map((i) => <li><a href={i.image}>{i.name}</a></li>)}
          </ul>
        }
      </main >

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  )
}
